# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_bluetooth_data <- function(input_file, progress_interval = 1000L) {
    .Call(`_wsbluetoothR_process_bluetooth_data`, input_file, progress_interval)
}

